### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by REPTILEHAUS** [bharshbarger/AutOSINT#26] opened 2017-04-15 03:57 UTC
Great tool - getting this error though 

```
Traceback (most recent call last):
  File "AutOSINT.py", line 329, in <module>
    main()
  File "AutOSINT.py", line 325, in main
    runAutosint.runQueries()
  File "AutOSINT.py", line 235, in runQueries
    self.scrapeResult = self.web_scraper.run(self.args, self.lookupList, self.reportDir, self.apiKeyDir)
  File "/Users/me/AutOSINT/modules/webscrape.py", line 117, in run
    vtJson = json.loads(response)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by REPTILEHAUS** [comment] 2017-04-15 10:47
and just wondering how you are adding Harvester to PATH ? Tried a couple of variations but none are working. BTW this is on OSX not Debian or Kali, seems to be working apart from Harvester not working and the JSON error.

export PATH="$PATH:~/theHarvester"
export PATH="$PATH:~/theHarvester/theHarvester.py"

**Comment by meta-l** [comment] 2017-04-18 15:18
theharvester is called from within the python script using subprocess.popen, so will use your OS' path. If you can run theharvester in terminal with no messing about it should just work.

I can't reproduce the json error on Linux.

**Comment by REPTILEHAUS** [comment] 2017-04-18 16:42
I call the harvester by setting an alias function in my ~/.bashrc file - from what I gather scripts cannot use these kind of alias' so I am curious how does this work because no matter what way I use the export PATH type it does not get invoked by AutOSINT

**Comment by meta-l** [comment] 2017-04-19 12:32
For your system, easiest workaround is to simply edit the AutOSINT theharvester.py module to call an absolute reference to theharvester.

**Comment by REPTILEHAUS** [comment] 2017-04-19 20:13
Tried both and still not working, Ive edited the scripts and added the absolute paths to those tools and its working perfectly now. 

All but that JSON error :)

Tried tinkering around with it but cant figure out what the problem is, it just reports that there was a scraping error on github and indeed

**Comment by bharshbarger** [comment] 2017-04-20 03:12
Found the cause for the scraping errors (missing imports). Fix inbound. Thanks for the report!

**Comment by REPTILEHAUS** [comment] 2017-04-20 11:22
Fantastic!! let me know when to do a fetch

**Comment by bharshbarger** [comment] 2017-04-20 16:10
merged into master. indeed job listings and virustotal domain report json should at least show up in the text files. still need more parsing for VT results to end up in the .doc

**Closed** 2017-09-23 15:23 UTC
